env:
  NODE_ENV: prod
  # Backend API URL for frontend to connect to backend health check
  BACKEND_HOST: http://localhost:8008

## Single Pod Containers
envSecrets:
  # MongoDB Configuration
  MONGODB_URI: shipyard-digital-twin

## should be used in case of multi-pod container i.e: both frontend and backend in one pod
sidecarContainers:
  - name: backend
    image: 795250896452.dkr.ecr.us-east-1.amazonaws.com/industrysolutions/shipyard-simulation-demo-backend:latest
    env:
      # MongoDB connection (from Kubernetes secret)
      - name: MONGODB_URI
        valueFrom:
          secretKeyRef:
            name: shipyard-digital-twin
            key: MONGODB_URI

## ----------------------------- Cloud Specific Configurations (For AWS only line 42 to 46 needed)-----------------------------

## Add IRSA configuration here, this is for AWS
serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-prod-cicd-irsa"
